# Generated by Django 3.2.12 on 2022-06-05 18:34

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_short', models.CharField(max_length=500)),
                ('description_long', models.TextField()),
                ('coordinates', jsonfield.fields.JSONField()),
            ],
        ),
    ]
