# Generated by Django 3.2.12 on 2022-06-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='place',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
