# Generated by Django 3.2.13 on 2022-06-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20220613_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(),
        ),
    ]
